language: c
compiler: gcc

services:
  - docker

matrix:
  include:
    - env:
        - ARCH=x86_64
        - DOCKER_IMAGE=quay.io/appimage/appimagebuild
    - env:
        - ARCH=i686
        - DOCKER_IMAGE=quay.io/appimage/appimagebuild-i386
    - env:
        - ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - libfuse-dev
            - desktop-file-utils
    - env:
        - ENABLE_COVERAGE=On
        - ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - libfuse-dev
            - desktop-file-utils
            - gcovr
            - lcov
    - env:
        - BUILD_DOCS
      addons:
        apt:
          update: true
          packages:
            - doxygen
            - python3-pip
      dist: xenial
      script:
        - cd docs && ../travis/build-docs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: docs

script:
  - bash travis/travis-build.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
